repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
    args: ["--maxkb=1000"] # Exception for Catch2 header since hook does not allow ignore
  - id: check-case-conflict
  - id: check-yaml
  - id: detect-private-key
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: cppcheck
    args: [ "src/*", "lib/*", "tst/*", "--suppress=*:include/*", 
      "--suppress=unmatchedSuppression", 
      "--suppress=missingIncludeSystem", 
      "--suppress=unusedFunction"]
  - id: cpplint
    args: ["--exclude=include"]