repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: detect-private-key
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: cppcheck
    args: [ "src/**/*.cpp", "tst/**/*.cpp",
      "--suppress=*:extern/*",
      "--suppress=*:*.hpp",
      "--suppress=unmatchedSuppression",
      "--suppress=missingIncludeSystem",
      "--suppress=missingInclude",
      "--suppress=checkersReport",
      "--suppress=unusedFunction"]
  - id: cpplint
    args: [
      "--exclude=extern",
      "--filter=-build/c++11,-readability/check,-build/include_subdir"
    ]
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
    - id: check-json5
