name: Build and run unit tests
run-name: ${{ github.actor }} has pushed a commit
on: [push]
jobs:
    Build-and-Test_Ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install OpenGL
              run: |
                echo "Installing OpenGL" && \
                    sudo apt update && \
                    sudo apt install --fix-missing \
                    libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            - name: Configure CMake
              run: |
                echo "Configuring CMake" && \
                    mkdir build && cd build && cmake ..
            - name: Build target binaries
              run: |
                echo "Building targets" && \
                    cd build && make && echo "Successful build"
            - name: Run unit tests
              run: |
                cd build && pwd && ls && ./BlackHoleViz_test && \
                    echo "Unit tests passed."