name: Build and run unit tests
run-name: ${{ github.actor }} has pushed a commit
on: [push]
jobs:
    Build-and-Test_Ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install OpenGL
              run: |
                echo "Installing OpenGL" && \
                    sudo apt update -y && \
                    sudo apt install -y --fix-missing \
                    libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            - name: Setup OpenGL
              uses: openrndr/setup-opengl@v1.1
            - name: GLEW Info
              run: xvfb-run glxinfo
            - name: Setup CMake
              uses: jwlawson/actions-setup-cmake@v1.13
            - name: Configure CMake targets
              run: |
                echo "Configuring CMake" && \
                    mkdir build && cd build && cmake ..
            - name: Build target binaries
              run: |
                echo "Building targets" && \
                    cd build && make && echo "Successful build"
            - name: Run unit tests
              run: |
                ctest --test-dir build --output-on-failure && \
                    echo "Unit tests passed."