name: Proof of Concept Build Actions
run-name: ${{ github.actor }} has pushed a commit
on: [push]
jobs:
    Build-with-GCC:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Checking out repository on ${{ runner.os }} server"
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: echo "${{ github.repository }} has been cloned successfully"
            - name: Install OpenGL
              run: |
                echo "Installing OpenGL" && \
                    sudo apt update && \
                    sudo apt install --fix-missing \
                    libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            - name: Configure CMake
              run: |
                echo "Configuring CMake" && \
                    mkdir build && cd build && cmake ..
            - name: Build executables
              run: |
                echo "Building targets" && \
                    pwd && ls && cd build && make . && echo "Successful build"
            - name: Run unit tests
              run: |
                ./build/BlackHoleViz_test && \
                    echo "Unit tests passed."
            - run: echo "Completed with status ${{ job.status }}"