name: Pull request merge hooks
run-name: "Merged pull request #${{ github.event.number }}"
on: 
  pull_request:
    types: 
      - closed
    branches:
      - 'main'
jobs:
  Reset-Dev-Branch:
    if: github.head_ref == 'dev' && github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Reset 'dev' branch to 'main'
        uses: nicksnell/action-reset-repo@master
        with:
          base_branch: main
          reset_branch: dev
