name: Dry run build and test
run-name: ${{ github.actor }} has submitted pull request #${{ github.event.number }}
on:
  pull_request:
    types:
      - opened
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**CMakeLists.txt'
      - '.github/workflows/pull-request-opened.yml'
jobs:
  Build-and-Test_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install OpenGL
        run: |
          echo "Installing OpenGL" && \
            sudo apt update -y && \
            sudo apt install -y --fix-missing \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libopenal-dev libgl1-mesa-dev
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Configure CMake targets
        run: |
          echo "Configuring CMake" && \
            mkdir build && cd build && cmake ..
      - name: Build target binaries
        run: |
          echo "Building targets" && \
            cd build && cmake --build . --target Basil_test && echo "Successful build"
      - name: Run unit tests
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            ctest --test-dir build --output-on-failure && \
              echo "Unit tests passed."